### ISSUE TITLE
Can't change margins. 

### ISSUE THREAD

**Issue by Brendan-Lanham** [rensa/unswthesisdown#1]
Hi James, 

I've been using unswthesisdown to format my thesis but can't change the margins? The oddsidemargin is set at 40mm but is coming out at 20mm, and visa versa for the evensidemargin. Width is set at 150mm. No matter what I change them too, the pdf output is the same, even if I make them 0. Any suggestions?

**Comment by jimjam-slam** [comment]
Hi @Brendan-Lanham! I actually had someone from UWA email me a month or two ago about margin problems (namely, even and odd pages are the wrong way around). Unfortunately I completely forgot to update the template (I'll try to do it this weekend), but I'll copy and paste from my email so that you can fix your problem right away.

_[This SO answer](https://tex.stackexchange.com/a/42051/133263) seems to suggest that settings with the geometry package is much easier than trying to set them manually. I tried commenting out those lines in [`unswthesis.cls` (lines 177–8, 181)](https://github.com/rensa/unswthesisdown/blob/46ba6b02c09a8289ca46e459e34746c720160a6b/inst/rmarkdown/templates/thesis/skeleton/unswthesis.cls#L177):_

```
% \setlength{\oddsidemargin}{20mm}
% \setlength{\evensidemargin}{40mm}
\setlength{\textwidth}{150mm}
% \setlength{\textheight}{9.0in}
% \setlength\topmargin{30mm}
```

_And adding margins to the existing use of geometry in [`template.tex` (line 47)](https://github.com/rensa/unswthesisdown/blob/46ba6b02c09a8289ca46e459e34746c720160a6b/inst/rmarkdown/templates/thesis/skeleton/template.tex#L47):_

`\usepackage[top=3cm,left=4cm,right=2cm,bottom=2cm]{geometry}`

_(According to the linked answer, left and right are synonymous for inner and outer respectively when your document class uses twoside._

I'll update the template ASAP, but if you modify the version in your project, hopefully that helps in the mean time!

**Comment by Brendan-Lanham** [comment]
This worked a treat! 

Thank you!
